baseURL = "https://apieszka.github.io/"
languageCode = "pl-PL"
title = "Aleksandra Pieszka"

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "img/profile.jpg"
  author = "Aleksandra Pieszka"
  description = "Blog Oli Pieszki"

  # Custom assets can be linked with their paths relative to static/
  custom_css = ["css/additional.css"]
  custom_js  = []

[params.social]
  Github        = "apieszka"
  LinkedIn      = "aleksandrapieszka"
  

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"
